[project]
name = "madtryx"
version = "0.1.0"
description = "Creates the templates and settings for MadTryX"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "appdirs>=1.4.4",
    "typer>=0.20.0",
    "tyx-schema>=0.2.11",
]
